# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


puts 'Arm data'

Bicep.create!(bicep_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-curl-front.mp4', bicep_workout: 'Dumbbell Curl', bicep_step_one: "Stand up straight with a dumbbell in each hand at arm's length.", bicep_step_two: "Raise one dumbbell and twist your forearm until it is vertical and your palm faces the shoulder.", bicep_step_three:"Lower to original position and repeat with opposite arm")
Bicep.create!(bicep_clip:'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-hammer-curl-front.mp4', bicep_workout: 'Dumbbell Hammer Curl', bicep_step_one: 'Hold the dumbbells with a neutral grip (thumbs facing the ceiling).', bicep_step_two: 'Slowly lift the dumbbell up to chest height', bicep_step_three: 'Return to starting position and repeat.')
Tricep.create!(tricep_clip:'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-skullcrusher-front_XhMR7N7.mp4', tricep_workout: 'Dumbbell Skullcrusher', tricep_step_one: 'Lay flat on the floor or a bench with your fists extended to the ceiling and a neutral grip.', tricep_step_two: 'Break at the elbows until your fists are by your temples.', tricep_step_three: 'Then extend your elbows and flex your tricep at the top.')
Tricep.create!(tricep_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-overhead-tricep-extension-front.mp4', tricep_workout: 'Seated Overhead Tricep Extension', tricep_step_one: 'Sit on the bench and hold a dumbbell with both hands. Raise the dumbbell overhead at arms length, holding the weight up with the palms of your hands.', tricep_step_two: 'Keep your elbows in while you lower the weight behind your head, your upper arms stationary.', tricep_step_three: 'Raise the weight back to starting position.')
Forearm.create!(forearm_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-wrist-curl-front.mp4', forearm_workout: 'Dumbbell Wrist Curl', forearm_step_one: 'Grip the dumbbell with your palm facing upwards with your forearm rested against the bench.', forearm_step_two: 'Slowly curl your wrist upwards in a semicircular motion.', forearm_step_three: 'Return to starting position and repeat.')
Forearm.create!(forearm_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-row-unilateral-front.mp4', forearm_workout: 'Dumbbell Row Unilateral', forearm_step_one: 'Brace your off arm against something stable (bench, box). Stagger your stance so your leg on the side of your working arm is back.', forearm_step_two: 'Try to get your torso to parallel with the ground. That will extend your range of motion.', forearm_step_three: "Let your arm hang freely and then pull your elbow back. Imagine you've got a tennis ball in your armpit and squeeze it each rep.")

puts 'Chest Data'

Chest.create(chest_clip: 'https://musclewiki.com/media/uploads/videos/branded/female-dumbbell-incline-chest-flys-front.mp4', chest_workout: 'Dumbbell Incline Chest Flys', chest_step_one: 'Lay flat on the bench and place your feet on the ground', chest_step_two: 'Begin the exercise with the dumbbells held together above your chest, elbows slightly bent.', chest_step_three: 'Simultaneously lower the weights to either side. Pause when the weights are parallel to the bench, then raise your arms to the starting position.');
Chest.create(chest_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-incline-bench-press-front.mp4', chest_workout: 'Incline Dumbbell Bench Press', chest_step_one: 'Raise the bench to a 30 - 45 degree angle', chest_step_two: 'Lay on the bench and set your feet on the ground.', chest_step_three: 'Raise the dumbbells with straight arms then slowly lower them to about shoulder width. Raise them again until your arms are locked and at the starting position again.');
Chest.create(chest_clip: 'https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-bench-press-side.mp4', chest_workout: 'Dumbbell Bench Press', chest_step_one: 'Lay flat on the bench with your feet on the ground. Raise the dumbbells until you have straight arms.', chest_step_two: 'Lower the dumbbells to your mid chest', chest_step_three: "Raise the dumbbells until you've locked your elbows.");

puts 'Stomach Data'

Stomach.create(stomach_clip: "https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-russian-twist-side.mp4", stomach_workout: "Dumbbell Russian Twist", stomach_step_one: "Sit on the floor and flex your knees and hips to a 90 degree angle.", stomach_step_two: "Your feet should be hovering off the ground. (If that's too hard start with heels on the floor)", stomach_step_three: "Rotate your upper spine to engage your obliques.")
Stomach.create(stomach_clip: "https://musclewiki.com/media/uploads/videos/branded/male-bodyweight-forearm-plank-front.mp4", stomach_workout: "Forearm Plank", stomach_step_one: "Place forearms on the ground with your elbows bent at a 90° angle aligned beneath your shoulders, with your arms parallel at shoulder-width.", stomach_step_two: "Your feet should be together, with only your toes touching the floor.", stomach_step_three: "Lift your belly off the floor and form a straight line from your heels to the crown of your head and hold.")
Stomach.create(stomach_clip: "https://musclewiki.com/media/uploads/videos/branded/female-bodyweight-leg-raises-front.mp4", stomach_workout: "Laying Leg Raises", stomach_step_one: "Lay on your back with your arms palms down on either side.", stomach_step_two: "Keep your legs together and as straight as possible. Slowly raise your legs to a 90° angle, pause at this position, or as high as you can reach your legs, and then slowly lower your legs back down.", stomach_step_three: "Duration of these movements should be slow so that you do not utilize momentum, enabling you to get the most out of the exercise.")

puts 'Legs Data'

Quad.create(quad_clip: "https://musclewiki.com/media/uploads/videos/branded/female-dumbbell-goblet-squat-side.mp4", quad_workout: "Dumbbell Goblet Squat", quad_step_one: "Hold the weight tucked into your upper chest area, keeping your elbows in. Your feet should be slightly wider than shoulder width.", quad_step_two: "Sink down into the squat, keeping your elbows inside the track of your knees.", quad_step_three: "Push through your heels while keeping your chest up and return to starting position.")
Quad.create(quad_clip: "https://musclewiki.com/media/uploads/videos/branded/male-machine-leg-extension-side.mp4", quad_workout: "Leg Extension", quad_step_one: "Sit on the machine with your back against the cushion and adjust the machine you are using so that your knees are at a 90 degree angle at the starting position.", quad_step_two: "Raise the weight by extending your knees outward, then lower your leg to the starting position.", quad_step_three: "Both movements should be done in a slow, controlled motion.")
Quad.create(quad_clip: "https://musclewiki.com/media/uploads/videos/branded/male-kettlebell-step-up-side.mp4", quad_workout: "Step Up", quad_step_one: "Standing up straight, using a bench as a step, raise one foot onto the bench and hold the kettlebell in the same arm as the straight leg.", quad_step_two: "Stand and bring both feet onto the bench.", quad_step_three: "Slowly lower your leg back down to the starting position an repeat.")
Hamstring.create(hamstring_clip: "https://musclewiki.com/media/uploads/videos/branded/male-cable-pull-through-front.mp4", hamstring_workout: "Pull Through", hamstring_step_one: "his exercise works best with a rope attachment but can be done with anything. The attachment should be set to the bottom of the machine.", hamstring_step_two: "Face away from the cable machine, straddle the cable itself, and grab the attachment. Walk a few steps away.", hamstring_step_three: "Break at the hips while maintaining a flat back and mostly extended knees. Push hips forward until you are back in a standing position.")
Hamstring.create(hamstring_clip: "https://musclewiki.com/media/uploads/videos/branded/female-barbell-stiff-leg-deadlift-front.mp4", hamstring_workout: "Stiff Leg Deadlifts", hamstring_step_one: "Stand with a barbell at your shins with your feet shoulder width apart. Bend forward at your hips and keep your knees as fully extended as possible.", hamstring_step_two: "Grab the barbell and then extend your hips while maintaining a straight back. From the standing position, lower the weight in a controlled manner.", hamstring_step_three: "You can either lower the weight to the floor or before you touch the floor, depending on your mobility.")
Hamstring.create(hamstring_clip: "https://musclewiki.com/media/uploads/videos/branded/female-dumbbell-goblet-good-morning-side.mp4", hamstring_workout: "Dumbbell Goblet Good Morning", hamstring_step_one: "Hold the dumbbell in a goblet position. With your elbows directly under your fists.", hamstring_step_two: "Push your hips back while leaving your knees MOSTLY extended. You should feel a stretch in your hamstrings.", hamstring_step_three: "When you feel the stretch push your hips forward until you're back in a standing position.")
Calve.create(calve_clip: "https://musclewiki.com/media/uploads/videos/branded/male-dumbbell-calf-raise-side.mp4", calve_workout: "Dumbbell Calf Raise", calve_step_one: "Stand tall with your feet on the ground.", calve_step_two: "You can put the the balls of your feet on top of a plate to extend the range of motion.", calve_step_three: "magine you have a string attached to your heels and pull your heels up toward the ceiling.")
Calve.create(calve_clip: "https://musclewiki.com/media/uploads/videos/branded/male-barbell-calve-raise-side.mp4", calve_workout: "Barbell Calf Raises", calve_step_one: "Place the bar on your back, start with feet flat on the ground", calve_step_two: "Extend your heels upwards while keeping your knees stationary, and pause at the contracted position.", calve_step_three: "Slowly return to the starting position. Repeat.")
Calve.create(calve_clip: "https://musclewiki.com/media/uploads/videos/branded/male-cable-calve-raise-front.mp4", calve_workout: "Cable Calve Raise", calve_step_one: "Use a straight bar or ez bar attachment with the cable set all the way to the bottom.", calve_step_two: "Walk a few steps back.", calve_step_three: "Pull your heels straight up until you feel a contraction in your calves and then back to original position.")